### ISSUE TITLE
Support Visual Studio Code as Notebook host

### ISSUE THREAD

**Issue by yGuy** [yWorks/yfiles-jupyter-graphs#1]
**Describe the bug**
The widget currently does not work in the Visual Studio Code environment.

**To Reproduce**
1. Open a notebook in Visual Studio Code and enable Notebook editing
2. Install the plugin
3. Try to run any of the examples
4. On Windows you won't see anything - the widget is simply missing. On Mac, you might see an image saying that only localhost and 127.0.0.1 are supported

**Expected behavior**
Ideally the widget would also work in Visual Studio Code which has superior code editing functionality.

**Additional context**
Unfortunately the Visual Studio Code environment is not perfectly compatible to JupyterLab or JupyterNotebook. Specifically custom widgets do not work out-of-the box and custom steps are necessary. It's not perfectly clear what these steps are and whether it is feasible in the case of this plugin.

**Plea for help**
If you can help us better understand how to properly implement this (and whether this is even feasible given the current VSC architecture), we'll be happy to add this useful feature.

**Comment by fskpf** [comment]
The Wiki pages of https://github.com/microsoft/vscode-jupyter also seem to contain some useful background information, e.g. [Component: IPyWidgets](https://github.com/microsoft/vscode-jupyter/wiki/Component:-IPyWidgets) or [IPyWidget Support in VS Code Python](https://github.com/microsoft/vscode-jupyter/wiki/IPyWidget-Support-in-VS-Code-Python).

**Comment by Jim-Salmons** [comment]
Rather than open a new issue, I have found that this great package suffers a similar gothca in PyCharm. After importing the library and instantiating a GraphWidget with a Networkx graph, running the cell returns the message "This notebook contains widget which is not supported by Intellij. See JavaScript logs for more info." A search for a relevant Javascript log was unsuccessful.

**Comment by yGuy** [comment]
Corresponding [issue](https://youtrack.jetbrains.com/issue/PY-46680/Jupyter-notebook-preview-where-are-the-Javascript-logs]) is on the JetBrains Bugtracker for the IntelliJ Issue. With VSCode, we might be able to solve this on our own, but without the help of JetBrains, this is going to be tough. So please also consider voting on [the JetBrains issue](https://youtrack.jetbrains.com/issue/PY-46680/Jupyter-notebook-preview-where-are-the-Javascript-logs).

**Comment by fskpf** [comment]
The widget should now work in VSCode.
