### ISSUE TITLE
Add export to graphml function to widget

### ISSUE THREAD

**Issue by enzococca** [yWorks/yfiles-jupyter-graphs#10]
If possible insert a function to export to graphml?

**Comment by yGuy** [comment]
Do you mean a function to export the graphml as a string variable to python? Could you suggest some API?  like 

`widget.export_GraphML()`?

You can already export the graph to graphml with one additional step, in an interactive manner: Open the graph in yEd-live with the button, and then use the save as file option from there.

**Comment by enzococca** [comment]
Hi sebastian, yes I mean to export like widget.export_graphml.

I wrote a parser xml to export for yed graphml from a dot file made by
graphviz.

If you are interested I can share with you

E

Il lun 27 giu 2022, 12:21 Sebastian Müller ***@***.***> ha
scritto:

**Comment by yGuy** [comment]
Regarding the dot file export/import. Does it do much more than the structure? yEd-Live already has basic graphviz dot file import - just drop the dot file into yed-live and it will load immediately.

**Comment by enzococca** [comment]
I forget to write:
The graphml generated I import in yed desktop after swimline I save it
again in graphml. This graphml I use like connector in blender for 3D
recostruction

E

Il lun 27 giu 2022, 16:51 Enzo Cocca ***@***.***> ha scritto:

**Comment by yGuy** [comment]
I am not convinced that this is a useful feature to have in a notebook. Exporting the graphml feels like trying to automate the layout algorithms, which is what we explicitly exclude in the license terms. For the interactive scenario, clicking the export to yed-live button will let you save the graphml in a separate step, interactively.
