### ISSUE TITLE
New version not working

### ISSUE THREAD

**Issue by SimonSAtSemantic** [yWorks/yfiles-jupyter-graphs#39]
**Describe the bug**
I am unable to remove the old version and replace it after the licence message.

**To Reproduce**
I used `pip uninstall yfiles_jupyter_graphs`, followed by `pip install yfiles_jupyter_graphs`.  

**Expected behavior**
Even after restarting the notebook kernel, the new version does not run.

**Screenshots**
```
The license of this widget has expired.

To update the license, please install the new free version of the widget from the [Python Package Index](https://pypi.org/).

In case this doesn't work for you, let us know on [GitHub](https://github.com/yWorks/yfiles-jupyter-graphs/issues).
```

**Desktop (please complete the following information):**
 - iOS
 - Chrome

**Additional context**

**Comment by SimonSAtSemantic** [comment]
After starting the whole note book rather than just the kernel - all good.

Thanks for the great utility :-)

**Comment by yGuy** [comment]
Correct. Sometimes it's enough to reload the browser, sometimes it needs a kernel restart. ipyWidgets are a bit strange in that regard.
