### ISSUE TITLE
Error: No version of module yfiles-jupyter-graphs is registered

### ISSUE THREAD

**Issue by NanisTe** [yWorks/yfiles-jupyter-graphs#40]
**Describe the bug**
The following error appears after having installed yfiles-jupyter-graphs.

**To Reproduce**
1. pip install yfiles-jupyter-graphs
2. done so in base conda environment and specific conda environment
3. running `from yfiles_jupyter_graphs import GraphWidget
# shows empty widget
GraphWidget()` in a notebook cell
Works by the way in Safari but not in chromium based Brave Browser

**Expected behavior**
see the widget.

**Screenshots**
<img width="1531" alt="image" src="https://github.com/yWorks/yfiles-jupyter-graphs/assets/17549266/365ee7ff-3356-4676-9a2d-585cdaeff038">

<img width="728" alt="image" src="https://github.com/yWorks/yfiles-jupyter-graphs/assets/17549266/246085f1-af46-4291-b012-d9e9f1377e8b">

<img width="710" alt="image" src="https://github.com/yWorks/yfiles-jupyter-graphs/assets/17549266/c5684a8b-dc36-4516-84e8-9e54fe804522">

**Desktop (please complete the following information):**
 - MacOs Sonoma 14.1 M2 arm64
 - Brave
 - [1.60.114](https://github.com/brave/brave-browser/tree/1.60.x)

**Additional context**

**Comment by yGuy** [comment]
Have you tried restarting the kernel after installing the module and/or reloading the jupyter notebook in the browser?
The error typically indicates that the Jupyter widget registry does not match the widgets registered in the running browser instance.

**Comment by NanisTe** [comment]
Yes. All of that. As mentioned opening the same instance from Safari works fine.

**Comment by fskpf** [comment]
I still believe this is a caching issue or something is blocked in the Brave browser. Even more so, if the very same instance works in a different browser.

I also just tested it successfully in a fresh environment with Brave browser, on Windows though.

Maybe you can also try to run it in a private Brave window. Maybe it makes a difference.

**Comment by yGuy** [comment]
Anything suspicious on the dev tools console?

**Comment by NanisTe** [comment]
It seems to be gone after multiple restarts of browser. There must have been something between Okta and Kubeflow having an effect on the Jupyterlab running inside the Kubeflow Notebook. Sorry for posting, but since I did multiple restarts and nothing changed I thought that could not have been related to some caching.
