### ISSUE TITLE
Feature: use the smart navigation feature from the yfiles demos

### ISSUE THREAD

**Issue by yGuy** [yWorks/yfiles-jupyter-graphs#48]
Being able to quickly jump from one end of an edge to the other one is super helpful in a browsing application.
Please add this feature for following edge paths from this demo:

https://live.yworks.com/demos/application-features/smart-click-navigation/

**Comment by fskpf** [comment]
Implemented with [v1.10](https://pypi.org/project/yfiles-jupyter-graphs/1.10.0/).
