### ISSUE TITLE
Feature request: Edge styles

### ISSUE THREAD

**Issue by kossyrev-bg** [yWorks/yfiles-jupyter-graphs#57]
I would like to be able to change the edge styles (such as source/target arrow shapes) like I can in yEd Live.

**Comment by fskpf** [comment]
`yfiles-jupyter-graphs` does not aim to provide the similar style customizability like yEd Live. It should provide a way to create a *useful* visualization for your data. If you need to create a very specific visualization, you can always export the diagram to yEd Live and then adjust the styling to your needs.

That said, we try to cover most use cases to some extend. For example, highlighting specific parts of the diagram, for which you can currently set the color of the items. Can you explain the context of your request? Does the arrow shape convey specific information in your case, or is it a case of disliking the current arrow shape?
