### ISSUE TITLE
GraphView cannot be created in JupyterLab

### ISSUE THREAD

**Issue by mjbonifa** [yWorks/yfiles-jupyter-graphs#63]
**Describe the bug**
We get the following javascript error when trying to view a graph

```
Open Browser Console for more detailed log - Double click to close this message]
Failed to create view for 'GraphView' from module 'yfiles-jupyter-graphs' with model 'GraphModel' from module 'yfiles-jupyter-graphs'
constructor@https://frontend/brcbat-mjbonifa-nb/lab/extensions/yfiles-jupyter-graphs/static/853.5ba5bc1eb2171a3f40a0.js?v=5ba5bc1eb2171a3f40a0:309:412535
3853/
```
**To Reproduce**
1. Install a bunch of stuff including yfiles packages
2. Create notebook
3. Run code
```
from yfiles_jupyter_graphs import GraphWidget
# shows empty widget
GraphWidget()
```
4. View error

**Expected behavior**
I would expect an empty widget to be displayed

**Desktop (please complete the following information):**
 - OS: RHEL7
 - Browser: Firefox, firefox.x86_64 0:128.4.0-1.el7_9 
 
**Server**
- OS: RHEL7
- Docker 20.10.9, build c2ea9bc
- Image: jupyter/datascience-notebook   latest
- JupyterLab v4.0.7

```
Selected Jupyter core packages...
IPython          : 8.16.1
ipykernel        : 6.25.2
ipywidgets       : 8.1.1
jupyter_client   : 8.4.0
jupyter_core     : 5.4.0
jupyter_server   : 2.8.0
jupyterlab       : 4.0.7
nbclient         : 0.8.0
nbconvert        : 7.9.2
nbformat         : 5.9.2
notebook         : 7.0.6
qtconsole        : not installed
traitlets        : 5.11.2

Python 3.11.6

JupyterLab v4.0.7
/opt/conda/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        yfiles-jupyter-graphs v1.9.0 enabled OK (python, yfiles_jupyter_graphs)
        jupyter-matplotlib v0.11.3 enabled OK
        nbdime-jupyterlab v2.2.0 enabled  X
        @jupyter-notebook/lab-extension v7.0.6 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.9 enabled OK (python, jupyterlab_widgets)
        @jupyterhub/jupyter-server-proxy v4.1.0 enabled OK
        @jupyterlab/git v0.41.0 enabled  X (python, jupyterlab-git)

   The following extensions are outdated:
        jupyterlab_pygments
        nbdime-jupyterlab
        @jupyterlab/git
        
   Consider checking if an update is available for these packages.

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
```

**Additional context**

None

**Comment by fskpf** [comment]
I have not seen this error message before but maybe it is related to the more common 
```
Failed to load model class 'GraphModel' from module 'yfiles-jupyter-graphs'
Error: No version of module yfiles-jupyter-graphs is registered
```

Have you tried restarting the kernel AND reloading the jupyter-lab window. In my experience, installing packages often requires to restart the entire environment.

Therefore, did you try such things and did it help?

**Comment by mjbonifa** [comment]
@fskpf Thanks for responding. I meant to let you know that this is resolved.

Essentially, this was a browser issue. The RHEL7 machine was running Firefox 128.4. I tested access the Jupyter from another machine with Windows/Firefox 133.0 and it worked - after reloading the browser page with F5 to get past the usual error ```Failed to load model class 'GraphModel' from module```

No amount of page reloading on RHEL7 Firefox 128.4 would resolve the original error but we have a way forward whilst RHEL7 was end of life from June 24 so being upgraded anyway. 

You can close the issue now.

**Comment by fskpf** [comment]
Thanks for the details.
