### ISSUE TITLE
License.md missing space :-)

### ISSUE THREAD

**Issue by ams1** [yWorks/yfiles-jupyter-graphs#7]
**Describe the bug**
When you come across such an INCREDIBLE repo:
1. you feel the urge to say "Thank you!" somehow (bugs seem to be the only quick option except the star)
```py
print("Thank you!\n" * 1000)
```
2. you start wondering why doesn't it have 30k stars (and then you see it's only 2 months old, hmm...)
3. you start thinking "for sure there must be a catch" (btw. I did NOT find any catch) and look at the license file - there I found the "bug" - `there is a space chr missing after the comma` 😄 (see below)

**To Reproduce**
1. Go to [LICENSE.md](https://github.com/yWorks/yfiles-jupyter-graphs/blob/main/LICENSE.md)
2. Scroll down to `1.2.ii`
3. See the missing space
```
... create derivative works,modify, translate, ...
                           ^
```
**Expected behavior**
There should be a space :-)

**Additional context**
OCD aside: big, BIG "thank you" for this (!)

**Comment by fskpf** [comment]
Thank you for the hint and your kind words. I've added the missing space 😊

**Comment by yGuy** [comment]
We don't even have a real home-page, but we soon will! 
Getting 30k stars would be awesome - and the more we get the more likely we are to invest into the project and add more features. So thank you for the kind words - keep spreading the word!
