### ISSUE TITLE
w.show() not working in jupyter notebook

### ISSUE THREAD

**Issue by SimonShapiro** [yWorks/yfiles-jupyter-graphs#9]
**Describe the bug**
I am not able to see the actual diagram, but I get no error messages.

**To Reproduce**
```
from networkx import connected_caveman_graph
from yfiles_jupyter_graphs import GraphWidget
w = GraphWidget()
w.show()

g = connected_caveman_graph(3, 4)
w.import_graph(g)
w.show()
```

**Expected behavior**
I expected to see the diagram as in the example in guthub.

**Screenshots**

**Desktop (please complete the following information):**
 - Mac M1
 - MacOs
 - Chrome
 - Notebook server 6.0.1
 - Ipython 7.27
 - Python 3.7.4

**Additional context**

**Comment by yGuy** [comment]
What *do* you see? Do you see the widget but just without a graph or nothing at all? No error messages whatsoever?

**Comment by yGuy** [comment]
Did you restart the notebook server after installing the widget?

**Comment by SimonShapiro** [comment]
Hi,

Thanks for coming back so quickly :-).

All good now.

I am so excited about the potential for this.  It's something I was hoping
to eventually be available.

Many thanks for building it.


Regards


Simon

**Comment by SimonShapiro** [comment]
I solved the problem by "close and halt" the notebook.
Then I went back to the directory listing in the browser and re-opened the notebook.
After that everything was fine.
